### ISSUE TITLE
Task Reconcilliation does not account for task names

### ISSUE THREAD

**Issue by abhay-agarwal** [mesosphere/hdfs#115]
Task reconciliation won't account for the task names, meaning that if the scheduler is restarted and subsequently a journal node or name node dies, the live state will not contain any information about which named tasks are running. The system may launch two `journalnode1`s or two `namenode1`s, putting the framework into an erroneous state.

**Comment by elingg** [comment]
Nice catch! Thanks, it seems the improvement in naming logic for namenodes and journalnodes that you added is not part of persisted state and used for reconciliation. If you could look into this, that would be great.
