### ISSUE TITLE
Dangling Executor for 15 minutes after slave restart

### ISSUE THREAD

**Issue by abhay-agarwal** [mesosphere/hdfs#117]
If a slave is restarted, the tasks running on the corresponding executor will detach from the parent process and continue to run. Since HDFS is now unaware of this, it will try to launch a new executor there. For the 15 minutes that the executor is left dangling before it shuts itself down, the new executor will error continuously.

**Comment by elingg** [comment]
Upon slave restart, I have seen the executor reregister with the slave successfully after the slave restarted. That said, if there is an issue here, we need to address it. We should be able to recover from slave restarts.

**Comment by abhay-agarwal** [comment]
Once I get a more robust FW uninstall sequence implemented, i'll close this issue. Otherwise there's too many moving parts.

**Comment by elingg** [comment]
Sure, let's rule out user error and make sure this wasn't just because something was not shutdown properly when uninstalling.

**Comment by elingg** [comment]
Is this safe to close @abhay-agarwal?

**Comment by elingg** [comment]
This actually seems to be related to this issue, https://issues.apache.org/jira/browse/MESOS-2605

**Comment by elingg** [comment]
This appears to be fixed with MESOS-2605.
