### ISSUE TITLE
No `hdfs.mesos` record in Mesos-DNS registered 

### ISSUE THREAD

**Issue by Y4Rv1K** [mesosphere/hdfs#122]
I'm trying to start hdfs on top of mesos using Microservices Infrastructure project from Cisco and I see that framework registered but all jobs mark as lost and I can't reach hdfs because `hdfs.mesos` record not exist. 

BTW marathon frameworks haven't create his records too but `leader.mesos` and `master.mess` works fine 

Can somebody help me figure out what is wrong with it?

**Comment by stevendborrelli** [comment]
Are you running mesos-dns? Microservices Infrastructure uses consul for dns, so your `mesos-site.xml` configuration file in that case would be `mesos-leader.service.consul` for mesos, and `marathon.service.consul` for marathon instances.

**Comment by Y4Rv1K** [comment]
Yes, I do. I'm using mesos-DNS on separate instance. It works ok.

And consul DNS still in development branch.

Problem is other. Doesn't looks like hdfs registers properly. All offers are rejected and no hdfs record in zookeeper.

**Comment by elingg** [comment]
Are the offers being rejected because of a lack of resources? With a small cluster, you may want to lower your settings for the different tasks. See mesos-site.xml.

**Comment by keithchambers** [comment]
@Y4Rv1K where you able to resolve this issue?

**Comment by Y4Rv1K** [comment]
I think that can be closed. Not actual right now.
