### ISSUE TITLE
Marathon env variables

### ISSUE THREAD

**Issue by ddispaltro** [mesosphere/hdfs#132]
Marathon requires env variables to be strings.  Simple fix is to convert the env values in the marathon.json to be strings.

**Comment by elingg** [comment]
Thanks @ddispaltro! Hey @nicgrayson, there is an issue in Marathon, and also the env variables in mesos-site.xml don't seem to be resolving. Could you address these issues? Another option is that I can revert the last PR until its fixed, but we would like to avoid that if possible.

**Comment by ddispaltro** [comment]
Yeah they are two separate issues, this one is simple, the other one #133 seems more complex.

**Comment by elingg** [comment]
After reverting the latest PR, this issue should be resolved. @nicgrayson is making a few fixes before merging that change in again. Feel free to reopen if this issue crops up again.
