### ISSUE TITLE
jetty.server ip

### ISSUE THREAD

**Issue by samek** [mesosphere/hdfs#137]
Is there a way do define which ip will be used for the distribution of the hdfs-mesos-0.1.1.tgz ?
Right now It takes my external ip which is not really what I would like.

**Comment by nicgrayson** [comment]
If it's a static ip you can set mesos.hdfs.framework.hostaddress in mesos-site.xml

**Comment by samek** [comment]
Thanks

**Comment by elingg** [comment]
Note need to make sure /etc/hosts contains the ip you want for your config server instead of 127.0.1.1 next to your hostname.

**Comment by elingg** [comment]
Feel free to reopen if there are further issues. Thanks!
