### ISSUE TITLE
expand documentation?

### ISSUE THREAD

**Issue by jtktam** [mesosphere/hdfs#139]
The build instructions and documentation is a bit lacking, I will try to document as I experiment on my own mesos setup. 

Some example *site files would make it easier, the one line instruction to customize the *site files don't really help

**Comment by jtktam** [comment]
nevermind.. i found the example *site files..

**Comment by kcao3** [comment]
@jtktam I am facing the same "wall" here. Is there any chance that you can share the example *site files that you found? Much thanks in advance!

**Comment by ddispaltro** [comment]
I think he's referring to https://github.com/mesosphere/hdfs/blob/master/example-conf/mesosphere-dcos/mesos-site.xml

**Comment by kcao3** [comment]
@ddispaltro thanks for pointing out the location of the example config files.
