### ISSUE TITLE
Nodes in mesos cluster are fetching uri from 127.0.0.1

### ISSUE THREAD

**Issue by boshido** [mesosphere/hdfs#144]
I try to follow installation until this step "./bin/hdfs-mesos".
And it is failed, so this is output from command.

>2015-06-25 16:13:34,106:1474(0x7fae5d4b3700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
>2015-06-25 16:13:34,106:1474(0x7fae5d4b3700):ZOO_INFO@log_env@716: Client environment:host.name=spark
>2015-06-25 16:13:34,106:1474(0x7fae5d4b3700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
>2015-06-25 16:13:34,106:1474(0x7fae5d4b3700):ZOO_INFO@log_env@724: Client environment:os.arch=3.16.0-30-generic
>2015-06-25 16:13:34,106:1474(0x7fae5d4b3700):ZOO_INFO@log_env@725: Client environment:os.version=#40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
>2015-06-25 16:13:34,106:1474(0x7fae5d4b3700):ZOO_INFO@log_env@733: Client environment:user.name=spark
>2015-06-25 16:13:34,106:1474(0x7fae5d4b3700):ZOO_INFO@log_env@741: Client environment:user.home=/home/spark
>2015-06-25 16:13:34,106:1474(0x7fae5d4b3700):ZOO_INFO@log_env@753: Client environment:user.dir=/home/spark/test/hdfs-mesos-0.1.1
2015-06-25 16:13:34,106:1474(0x7fae5d4b3700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=192.168.0.50:2181 sessionTimeout=20000 watcher=0x7fae6541fa60 sessionId=0 sessionPasswd=<null> context=0x7fae14001160 flags=0
2015-06-25 16:13:34,106:1474(0x7fae2e7fc700):ZOO_INFO@check_events@1703: initiated connection to server [192.168.0.50:2181]
2015-06-25 16:13:34,113:1474(0x7fae2e7fc700):ZOO_INFO@check_events@1750: session establishment complete on server [192.168.0.50:2181], sessionId=0x14e29ee69ea000c, negotiated timeout=20000
2015-06-25 16:13:34,127:1474(0x7fae5dcb4700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-06-25 16:13:34,127:1474(0x7fae5dcb4700):ZOO_INFO@log_env@716: Client environment:host.name=spark
2015-06-25 16:13:34,127:1474(0x7fae5dcb4700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-06-25 16:13:34,127:1474(0x7fae5dcb4700):ZOO_INFO@log_env@724: Client environment:os.arch=3.16.0-30-generic
2015-06-25 16:13:34,127:1474(0x7fae5dcb4700):ZOO_INFO@log_env@725: Client environment:os.version=#40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
2015-06-25 16:13:34,127:1474(0x7fae5dcb4700):ZOO_INFO@log_env@733: Client environment:user.name=spark
2015-06-25 16:13:34,127:1474(0x7fae5dcb4700):ZOO_INFO@log_env@741: Client environment:user.home=/home/spark
2015-06-25 16:13:34,127:1474(0x7fae5dcb4700):ZOO_INFO@log_env@753: Client environment:user.dir=/home/spark/test/hdfs-mesos-0.1.1
2015-06-25 16:13:34,127:1474(0x7fae5dcb4700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=192.168.0.50:2181 sessionTimeout=20000 watcher=0x7fae6541fa60 sessionId=0 sessionPasswd=<null> context=0x7fae24001840 flags=0
2015-06-25 16:13:34,127:1474(0x7fae2d7fa700):ZOO_INFO@check_events@1703: initiated connection to server [192.168.0.50:2181]
2015-06-25 16:13:34,128:1474(0x7fae2d7fa700):ZOO_INFO@check_events@1750: session establishment complete on server [192.168.0.50:2181], sessionId=0x14e29ee69ea000d, negotiated timeout=20000
2015-06-25 16:13:34,136:1474(0x7fae2ffff700):ZOO_INFO@log_env@712: Client environment:zookeeper.version=zookeeper C client 3.4.5
2015-06-25 16:13:34,136:1474(0x7fae2ffff700):ZOO_INFO@log_env@716: Client environment:host.name=spark
2015-06-25 16:13:34,136:1474(0x7fae2ffff700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
2015-06-25 16:13:34,136:1474(0x7fae2ffff700):ZOO_INFO@log_env@724: Client environment:os.arch=3.16.0-30-generic
2015-06-25 16:13:34,136:1474(0x7fae2ffff700):ZOO_INFO@log_env@725: Client environment:os.version=#40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015
I0625 16:13:34.136083  1503 sched.cpp:157] Version: 0.22.1
2015-06-25 16:13:34,136:1474(0x7fae2ffff700):ZOO_INFO@log_env@733: Client environment:user.name=spark
2015-06-25 16:13:34,136:1474(0x7fae2ffff700):ZOO_INFO@log_env@741: Client environment:user.home=/home/spark
2015-06-25 16:13:34,136:1474(0x7fae2ffff700):ZOO_INFO@log_env@753: Client environment:user.dir=/home/spark/test/hdfs-mesos-0.1.1
2015-06-25 16:13:34,136:1474(0x7fae2ffff700):ZOO_INFO@zookeeper_init@786: Initiating client connection, host=192.168.0.50:2181 sessionTimeout=10000 watcher=0x7fae6541fa60 sessionId=0 sessionPasswd=<null> context=0x7fae18001490 flags=0
2015-06-25 16:13:34,136:1474(0x7fae1ffff700):ZOO_INFO@check_events@1703: initiated connection to server [192.168.0.50:2181]
2015-06-25 16:13:34,137:1474(0x7fae1ffff700):ZOO_INFO@check_events@1750: session establishment complete on server [192.168.0.50:2181], sessionId=0x14e29ee69ea000e, negotiated timeout=10000
I0625 16:13:34.138624  1496 group.cpp:313] Group process (group(1)@127.0.1.1:53364) connected to ZooKeeper
I0625 16:13:34.138671  1496 group.cpp:790] Syncing group operations: queue size (joins, cancels, datas) = (0, 0, 0)
I0625 16:13:34.138689  1496 group.cpp:385] Trying to create path '/mesos' in ZooKeeper
I0625 16:13:34.139189  1497 detector.cpp:138] Detected a new leader: (id='21')
I0625 16:13:34.139264  1497 group.cpp:659] Trying to get '/mesos/info_0000000021' in ZooKeeper
I0625 16:13:34.139485  1493 detector.cpp:452] A new leading master (UPID=master@192.168.0.50:5050) is detected
I0625 16:13:34.139528  1497 sched.cpp:254] New master detected at master@192.168.0.50:5050
I0625 16:13:34.139637  1497 sched.cpp:264] No credentials provided. Attempting to register without authentication
I0625 16:13:34.140396  1497 sched.cpp:448] Framework registered with 20150625-115711-838904000-5050-3314-0005
16:13:34.144 [Thread-2] INFO  org.apache.mesos.hdfs.Scheduler - Registered framework frameworkId=20150625-115711-838904000-5050-3314-0005
16:13:34.145 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @461ms
16:13:34.154 [Thread-4] INFO  org.apache.mesos.hdfs.Scheduler - Received 2 offers
16:13:34.155 [Thread-4] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:13:34.157 [Thread-4] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:13:34.162 [Thread-5] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.journalnode.journalnode.NodeExecutor.1435223582565 state=TASK_LOST message='Executor terminated' stagingTasks.size=0
16:13:34.173 [main] INFO  org.eclipse.jetty.server.Server - jetty-9.2.z-SNAPSHOT
16:13:34.192 [main] INFO  o.e.jetty.server.ServerConnector - Started ServerConnector@71e84944{HTTP/1.1}{0.0.0.0:8765}
16:13:34.192 [main] INFO  org.eclipse.jetty.server.Server - Started @511ms
16:13:39.584 [Thread-15] INFO  org.apache.mesos.hdfs.Scheduler - Received 2 offers
16:13:39.585 [Thread-15] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:13:39.585 [Thread-15] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:13:44.587 [Thread-16] INFO  org.apache.mesos.hdfs.Scheduler - Received 2 offers
16:13:44.587 [Thread-16] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:13:44.588 [Thread-16] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:13:49.596 [Thread-17] INFO  org.apache.mesos.hdfs.Scheduler - Received 2 offers
16:13:49.596 [Thread-17] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:13:49.596 [Thread-17] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:13:55.593 [Thread-18] INFO  org.apache.mesos.hdfs.Scheduler - Received 2 offers
16:13:55.593 [Thread-18] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:13:55.593 [Thread-18] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:14:01.596 [Thread-19] INFO  org.apache.mesos.hdfs.Scheduler - Received 2 offers
16:14:01.596 [Thread-19] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:14:01.596 [Thread-19] INFO  org.apache.mesos.hdfs.Scheduler - Declining offers while reconciling tasks
16:14:04.146 [Timer-0] INFO  org.apache.mesos.hdfs.Scheduler - Current persistent state:
16:14:04.148 [Timer-0] INFO  org.apache.mesos.hdfs.Scheduler - JournalNodes: {192.168.0.52=null}, {}
16:14:04.149 [Timer-0] INFO  org.apache.mesos.hdfs.Scheduler - NameNodes: {}, {}
16:14:04.150 [Timer-0] INFO  org.apache.mesos.hdfs.Scheduler - DataNodes: {}
16:14:06.599 [Thread-20] INFO  org.apache.mesos.hdfs.Scheduler - Received 2 offers
16:14:06.600 [Thread-20] INFO  org.apache.mesos.hdfs.Scheduler - [192.168.0.52]
16:14:06.601 [Thread-20] INFO  org.apache.mesos.hdfs.Scheduler - [192.168.0.52]
16:14:06.601 [Thread-20] INFO  org.apache.mesos.hdfs.Scheduler - Launching node of type journalnode with tasks [journalnode]
16:14:06.915 [Thread-21] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.journalnode.journalnode.NodeExecutor.1435223646601 state=TASK_LOST message='Executor terminated' stagingTasks.size=1
16:14:07.600 [Thread-22] INFO  org.apache.mesos.hdfs.Scheduler - Received 1 offers
16:14:07.601 [Thread-22] INFO  org.apache.mesos.hdfs.Scheduler - [192.168.0.52]
16:14:07.601 [Thread-22] INFO  org.apache.mesos.hdfs.Scheduler - Launching node of type journalnode with tasks [journalnode]
16:14:07.821 [Thread-23] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.journalnode.journalnode.NodeExecutor.1435223647601 state=TASK_LOST message='Executor terminated' stagingTasks.size=1
16:14:08.601 [Thread-24] INFO  org.apache.mesos.hdfs.Scheduler - Received 1 offers
16:14:08.601 [Thread-24] INFO  org.apache.mesos.hdfs.Scheduler - [192.168.0.52]
16:14:08.602 [Thread-24] INFO  org.apache.mesos.hdfs.Scheduler - Launching node of type journalnode with tasks [journalnode]
16:14:08.826 [Thread-25] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.journalnode.journalnode.NodeExecutor.1435223648602 state=TASK_LOST message='Executor terminated' stagingTasks.size=1
16:14:09.601 [Thread-26] INFO  org.apache.mesos.hdfs.Scheduler - Received 1 offers
16:14:09.602 [Thread-26] INFO  org.apache.mesos.hdfs.Scheduler - [192.168.0.52]
16:14:09.602 [Thread-26] INFO  org.apache.mesos.hdfs.Scheduler - Launching node of type journalnode with tasks [journalnode]
16:14:09.835 [Thread-27] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.journalnode.journalnode.NodeExecutor.1435223649602 state=TASK_LOST message='Executor terminated' stagingTasks.size=1
16:14:10.602 [Thread-28] INFO  org.apache.mesos.hdfs.Scheduler - Received 1 offers
16:14:10.602 [Thread-28] INFO  org.apache.mesos.hdfs.Scheduler - [192.168.0.52]
16:14:10.602 [Thread-28] INFO  org.apache.mesos.hdfs.Scheduler - Launching node of type journalnode with tasks [journalnode]
16:14:10.843 [Thread-29] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.journalnode.journalnode.NodeExecutor.1435223650602 state=TASK_LOST message='Executor terminated' stagingTasks.size=1
16:14:11.602 [Thread-30] INFO  org.apache.mesos.hdfs.Scheduler - Received 1 offers
16:14:11.603 [Thread-30] INFO  org.apache.mesos.hdfs.Scheduler - [192.168.0.52]
16:14:11.603 [Thread-30] INFO  org.apache.mesos.hdfs.Scheduler - Launching node of type journalnode with tasks [journalnode]
16:14:11.848 [Thread-31] INFO  org.apache.mesos.hdfs.Scheduler - Received status update for taskId=task.journalnode.journalnode.NodeExecutor.1435223651603 state=TASK_LOST message='Executor terminated' stagingTasks.size=1

This is stderr from cluster node
![screen shot 2558-06-25 at 4 16 10 pm](https://cloud.githubusercontent.com/assets/3489862/8351181/9e08efe4-1b55-11e5-9c33-94d4d5a3e49a.png)

How can I fix this error?
I try to config something that relates to master uri in "mesos-site.xml" file 
but nothing change. 

And I'm very sorry for my English.

**Comment by teamsoo** [comment]
I'm facing the same problem here. Anyone knows how to fix this?

setting
```
<property>
  <name>mesos.hdfs.executor.uri</name>
  <value>master</value>
</property>
```

in mesos-site.xml doesn't help.

I've checked that http://master:8765/hdfs-mesos-0.1.1.tgz works. How can I change 127.0.0.1 to something else?

Thanks.

**Comment by F21** [comment]
Are you guys using mesos-dns? I just noticed that I have `journalnode1` running on my mesos-master node, but if I log into a slave and do `nslookup journalnode1.hdfs.mesos`, it returns `127.0.1.1`.

**Comment by boshido** [comment]
Thanks for replying me @F21 
I'm installed hdfs on mesos-master node without mesos-dns or any configuration that relate to mesos-dns.
I just use ip address in mesos configuration.

Does it ok to do like that ?

**Comment by elingg** [comment]
Yes, it's okay to do this, but instead of using mesos.hdfs.executor.uri, use mesos.hdfs.executor.path and point to the Path where your executor is located. The default value is one directory above (..), but you can set the exact path.

  public String getExecutorPath() {
    return getConf().get("mesos.hdfs.executor.path", "..");
  }

**Comment by elingg** [comment]
Notice that mesos.hdfs.executor.uri is not used at all by the config since we instead point to the path. Please let me know if setting the path to your executor works properly for you. Thanks!

**Comment by elingg** [comment]
Another important thing to note: Note need to make sure /etc/hosts contains the ip you want for your config server instead of 127.0.1.1 next to your hostname to make it work.  cc @teamsoo, @boshido

**Comment by teamsoo** [comment]
Thank you @elingg , I've checked my /etc/hosts and change the line

    127.0.0.1      hostname

to

    192.168.0.xx hostname

and now I can see the active tasks running.

Now, I'm going to check if it's working but I notice that inside hdfs-mesos-0.1.1/bin there is no hadoop??

Where/How can I run test command

    hadoop fs -ls hdfs://hdfs/ should show nothing for starters
    hadoop fs -put /path/to/src_file hdfs://hdfs/
    hadoop fs -ls hdfs://hdfs/ should now list src_file

**Comment by boshido** [comment]
@elingg Thanks 
I solved the problem now.
The problem was that my server hostname was resolving the wrong IP address.

**Comment by elingg** [comment]
Hi @boshido, you can run the test command in any of your slave nodes where HDFS is running. Let me know if there's anything further.

**Comment by teamsoo** [comment]
Hi @elingg ,

May I ask how can I run test command ex. *"hadoop fs -ls hdfs://hdfs/"* when my bin contains only *hdfs-mesos*

and will the *hdfs://hdfs/* works out of the box. Should I set *hdfs* to master IP in */etc/hosts*

Thanks,
Phakin

**Comment by teamsoo** [comment]
I see that after adding one more node. Data Node shows up on my cluster.

Thanks @elingg , cheer!

**Comment by elingg** [comment]
Great, @teamsoo!
