### ISSUE TITLE
HA HDFS on Mesos Cluster - Installation/Getting Started questions

### ISSUE THREAD

**Issue by kcao3** [mesosphere/hdfs#145]
Hello,

I have a running Mesos cluster with one master node and 2 slave nodes. 
Currently I do not have Hadoop pre-installed in my Mesos cluster and would like to install HA HDFS 
on this cluster. I have a few questions regarding the installation process:

1. The following statement is obtained from the documentation instruction:
	"Starts 1 active NameNode (with JournalNode and ZKFC), 1 standby NN (+JN,ZKFC), 1 JN, and everything else is DataNodes." 
In a 1master-2slave-Mesos cluter, does anyone know exactly WHERE AND HOW to run these daemons, including the active NameNode, the standby NameNode, the JournalNode, and the DataNodes.	

2.  The prerequisite 3 from the documentation states that $JAVA_HOME needs to be set on the host running the HDFS scheduler. So, in a 1master-2slave-Mesos cluster, which node do you run the HDFS scheduler on (the Mesos master, or one of the two Mesos slaves, or all nodes)? 	

3.  The installation step 1 from the documentation instruction indicates that I need to 	update the file hdfs-mesos-*.tgz to A node in my Mesos cluster. Does the 'NODE' in this context imply the Mesos master, the Mesos slave node, or any node in a cluster? In other words, in a 1master-2slave-Mesos cluster, where do you have the hdfs-mesos-* directory and its *-site.xml configuration files setup? Can they be placed on any node (slave/master) in the Mesos cluster or they must be placed only on the Mesos master? 
	
4.  In the example configuration file hdfs-site.xml, which can be obtained at this link:	https://github.com/mesosphere/hdfs/blob/master/example-conf/mesosphere-dcos/hdfs-site.xml, the "dfs.ha.namenodes.hdfs" property indicates that there are two NameNode running in the cluster: nn1 and nn2. Also this configuration indicates that the NameNode daemon is running at port 50071 and 50070 on the following hosts: namenode1.hdfs.mesos and namenode2.hdfs.mesos.The documentation instruction does NOT show how to run the NameNode daemon. Does anyone know how?
Also, in this same configuration file, the "dfs.namenode.shared.edits.dir" property indicates 	that there are three JournalNode daemon running in the cluster at the following host:port journalnode1.hdfs.mesos:8485, journalnode2.hdfs.mesos:8485, and journalnode3.hdfs.mesos:8485.
On a 1master-2slave Mesos cluster, does anyone know where and how to launch the JournalNode daemon?

Thank you very much for your time and help.

**Comment by jtktam** [comment]
once you compile the tgz file according to the instructions, you just copy it to any node in your mesos cluster.  untar it and run ./bin/hdfs-mesos

it will run the scheduler which will deploy the framework and tasks automatically, no need to do any more setup

if you need any more help, just let me know

**Comment by jtktam** [comment]
feel free to direct email me if you need to

**Comment by elingg** [comment]
Thanks @jtktam! Also, I am glad to help as well if anything additional is needed.

**Comment by kcao3** [comment]
So, I was able to start my HDFS-Mesos. However, the web console, it seems to me my journalnode1 task started but failed repeatedly. From the stderr log on the slave where the task launched indicate that it when the task started, it downloaded the file, named "hdfs-mesos-0.1.1.tgz" from the HDFS scheduler at port 8765. 
However, I believe for some unknown reason this file is CORRUPTED and the task dies because it failed to extract this corrupted file. The following is the exact error that shows on the stderr output when running task:

I0625 17:54:47.809825  9073 fetcher.cpp:214] Fetching URI 'http://10.0.2.5:8765/hdfs-mesos-0.1.1.tgz'
I0625 17:54:47.809953  9073 fetcher.cpp:125] Fetching URI 'http://10.0.2.5:8765/hdfs-mesos-0.1.1.tgz' with os::net
I0625 17:54:47.809968  9073 fetcher.cpp:135] Downloading 'http://10.0.2.5:8765/hdfs-mesos-0.1.1.tgz' to 
'/tmp/mesos/slaves/20150623-105318-84017162-5050-2338-S10/frameworks/20150623-105318-84017162-5050-2338-0000/
executors/executor.journalnode.NodeExecutor.1435269000211/runs/8a10ff8c-c9b7-48fd-8b72-1b3130f2f58d/
hdfs-mesos-0.1.1.tgz'

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Failed to extract /tmp/mesos/slaves/20150623-105318-84017162-5050-2338-S10/frameworks/
20150623-105318-84017162-5050-2338-0000/executors/executor.journalnode.NodeExecutor.1435269000211/
runs/8a10ff8c-c9b7-48fd-8b72-1b3130f2f58d/hdfs-mesos-0.1.1.tgz:
Failed to extract: command tar -C '/tmp/mesos/slaves/20150623-105318-84017162-5050-2338-S10/
frameworks/20150623-105318-84017162-5050-2338-0000/executors/executor.journalnode.NodeExecutor.
1435269000211/runs/8a10ff8c-c9b7-48fd-8b72-1b3130f2f58d' 
-xf '/tmp/mesos/slaves/20150623-105318-84017162-5050-2338-S10/frameworks/
20150623-105318-84017162-5050-2338-0000/executors/executor.journalnode.NodeExecutor.1435269000211/
runs/8a10ff8c-c9b7-48fd-8b72-1b3130f2f58d/hdfs-mesos-0.1.1.tgz' exited with status: 512
Failed to synchronize with slave (it's probably exited)

Does anyone have any idea what the "hdfs-mesos-0.1.1.tgz" file is CORRUPTED when the command ./bin/hdfs-mesos is running?

**Comment by elingg** [comment]
Yes, I know the exact issue here. Please specify the full path to mesos.hdfs.executor.path in your mesos-site.xml. This should be the path that contains hdfs-mesos-executor-0.1.1.tgz assuming you are using the latest code.

**Comment by elingg** [comment]
Probably some better docs could be added here. Doc PR's welcome or once you get it working if you would like to let me know the steps you took, I can add the docs. :+1:

**Comment by kcao3** [comment]
@elingg Thank you for your help. I now have my three JournalNodes running in my Mesos cluster. However, for some unknown reason, NO NameNode, ZKFC, and DataNode are launched. From the terminal console where I launched the ./bin/hdfs-mesos command, I receive this exact error:

3:41:28.886 [Thread-213] INFO  org.apache.mesos.hdfs.Scheduler - Received 1 offers
13:41:28.887 [Thread-213] INFO  org.apache.mesos.hdfs.Scheduler - Resolving DNS for journalnode3.hdfs.mesos
13:41:28.887 [Thread-213] WARN  org.apache.mesos.hdfs.Scheduler - Couldn't resolve host journalnode3.hdfs.mesos

Do you have any idea what's going on? Do I need to install Mesos DNS on my Mesos cluster in order to launch HA HDFS on Mesos?

**Comment by elingg** [comment]
hello @kcao3, the most likely cause is lack of resources. Mesos DNS will resolve after some amount of time, but if there are no more resources, you will not be able to launch the additional nodes. Make sure you have a minimum of 4 slave nodes. You can adjust the memory and cpu requirements to make them smaller in your configuration files, but if you do, please note that you will not be able to store as much data.

**Comment by elingg** [comment]
As a side note here, if you haven't installed Mesos DNS, then you shouldn't use the Mesos DNS configuration. You should use the default configuration.

**Comment by kcao3** [comment]
@elingg, after switching to use the default configuration files, I got all the HA HDFS tasks running in Mesos. Thanks again for your help!

**Comment by elingg** [comment]
Awesome @kcao3 !

**Comment by BhavnaChoubey** [comment]
I tried the same steps mentioned in URL https://github.com/mesosphere/hdfs but on running ./bin/hdfs-mesos getting error as :
Error: Could not find or load main class org.apache.mesos.hdfs.scheduler.Main
Any idea about the same ?
