### ISSUE TITLE
Can't run hadoop bin on master node 

### ISSUE THREAD

**Issue by boshido** [mesosphere/hdfs#146]
Below is the summary of my progress of the installation.
I can't find the hadoop bin in the extracted hdfs-mesos directory.
Should the hadoop bin be there or do I need to install hadoop on mesos separately?

![screen shot 2558-06-26 at 2 51 25 pm](https://cloud.githubusercontent.com/assets/3489862/8373016/e18c906e-1c12-11e5-8b2c-a8de6384c32f.png)

**Comment by elingg** [comment]
The first issue I see here is you will need a minimum of 4 slaves to run this framework successfully. When I cd into hdfs-mesos-0.1.1 this is what I see:

cd hdfs-mesos-0.1.1
$ ls
bin                           hdfs-mesos-executor-0.1.1.tgz
etc                           lib

To start hdfs, you will run ./bin/hdfs-mesos

**Comment by elingg** [comment]
Hi @boshido, based on your other issue being closed, it seems you have gotten things figured out so I will close this as well. Feel free to reopen if there are still issues.

**Comment by boshido** [comment]
@elingg Yes I can run mesos-hdfs now thank you for helping me.
