### ISSUE TITLE
HA HDFS in Mesos - Unable to browse HDFS from NameNodeWebUI

### ISSUE THREAD

**Issue by kcao3** [mesosphere/hdfs#149]
Hello,
I have HA HDFS installed and running in my Mesos cluster. From a client machine, I was able to browse the HDFS by running the following command: hadoop fs -ls hdfs://hdfs/. I was also able to upload files from the local machine to HA HDFS using command such as hadoop fs -put... 
However, from the WebUI of the active NameNode, for some  unknown reason I was not able browse the directory of HA HDFS. The following is a screenshot of my NameNodeWebUI that shows the actual error:

![namenodewebui](https://cloud.githubusercontent.com/assets/11382916/8434923/74691cc0-1f1c-11e5-9ec8-98447e11d0ba.png)

Does anyone know the cause of this issue and how to resolve it? Thanks in advance.

**Comment by elingg** [comment]
hello @kcao3, you have 2 NameNodes running. One is standby, the other is active. Please navigate to the port of your active NN at port 50070. You are currently looking at the UI for the standby NN.

**Comment by kcao3** [comment]
Yes! It turns out in my Mesos cluster, NameNode1 is the standby and NameNode2 is actually the active one. In HA HDFS, is there a proper way to determine which one is which? Anyway, this is obviously not a problem.

**Comment by elingg** [comment]
There are some commands you can run to determine which one is active. We also plan on adding a link to the active Web UI as a feature.
