### ISSUE TITLE
Add the support for defining the mesos constraints while running the hdfs framework

### ISSUE THREAD

**Issue by nigoel** [mesosphere/hdfs#185]
We have requirement to run the hdfs task only on specific slaves which are storage based hi-end machines. Such machines are tagged with the mesos attributes and should only be used for running the hdfs tasks.

Mesos has support for adding tags on slave and framework can select on basis of that.
http://mesos.apache.org/documentation/attributes-resources/

**Comment by elingg** [comment]
Fix for this was merged. Thanks @nigoel
