### ISSUE TITLE
LD_LIBRARY_PATH not correctly set for executors

### ISSUE THREAD

**Issue by F21** [mesosphere/hdfs#204]
I am running mesos 0.24.0 with Marathon 0.10.1 on CoreOS 808.0.0.

Mesos is built with the prefix `/opt/test/mesos/`. On my CoreOS nodes, mesos is also deployed to `/opt/test/mesos`.

My mesos slaves are started using systemd and the systemd unit files sets the environment variable: `LD_LIBRARY_PATH=/opt/test/mesos/lib`.

In addition, I am also starting my mesos-slaves with the `executor_environment_variable` flag: `--executor_environment_variables='{"LD_LIBRARY_PATH": "/opt/test/mesos/lib"}'`.

When starting the scheduler using Marathon, I also set the `LD_LIBRARY_PATH` environment variable to `/opt/test/mesos/lib`.

The scheduler starts fine. However, when it attempts to start the executor (journal node in my case), it fails because it is unable to load a shared library.

If I inspect `stdout`, it is apparent that the `LD_LIBRARY_PATH` environment variables I have set is not used:

```
HADOOP_DATANODE_OPTS=-Xmx512m -Xms512m
MESOS_DIRECTORY=/tmp/mesos/slaves/20150920-091313-169978048-5050-1315-S1/frameworks/20150920-091313-169978048-5050-1315-0001/executors/executor.journalnode.NodeExecutor.1442742836789/runs/c2241168-e8de-472f-abad-3749262b99b5
LD_LIBRARY_PATH=/usr/local/lib
MESOS_EXECUTOR_ID=executor.journalnode.NodeExecutor.1442742836789
HADOOP_HEAPSIZE=512
PATH=/opt/test/java/bin:/usr/sbin:/usr/bin
PWD=/tmp/mesos/slaves/20150920-091313-169978048-5050-1315-S1/frameworks/20150920-091313-169978048-5050-1315-0001/executors/executor.journalnode.NodeExecutor.1442742836789/runs/c2241168-e8de-472f-abad-3749262b99b5
JAVA_HOME=/tmp/mesos/slaves/20150920-091313-169978048-5050-1315-S1/frameworks/20150920-091313-169978048-5050-1315-0001/executors/executor.journalnode.NodeExecutor.1442742836789/runs/c2241168-e8de-472f-abad-3749262b99b5/jre1.7.0_76
MESOS_NATIVE_LIBRARY=/opt/test/mesos/lib/libmesos-0.24.0.so
HADOOP_OPTS=-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:+UseTLAB -XX:+AggressiveOpts -XX:+UseCompressedOops -XX:+UseFastEmptyMethods -XX:+UseFastAccessorMethods -Xss256k -XX:+AlwaysPreTouch -XX:+UseParNewGC -Djava.library.path=/usr/lib:/usr/local/lib:lib/native
MESOS_SLAVE_PID=slave(1)@192.168.33.11:5051
MESOS_FRAMEWORK_ID=20150920-091313-169978048-5050-1315-0001
MESOS_CHECKPOINT=1
EXECUTOR_OPTS=-Xmx256m -Xms256m
SHLVL=1
LIBPROCESS_PORT=0
HADOOP_NAMENODE_OPTS=-Xmx512m -Xms512m
MESOS_SLAVE_ID=20150920-091313-169978048-5050-1315-S1
MESOS_RECOVERY_TIMEOUT=15mins
_=/usr/bin/env
Warning: MESOS_NATIVE_LIBRARY is deprecated, use MESOS_NATIVE_JAVA_LIBRARY instead. Future releases will not support JNI bindings via MESOS_NATIVE_LIBRARY.
```

For some reason, the executor is still using `/usr/local/lib` as its `LD_LIBRARY_PATH` rather than `/opt/test/mesos/lib`.

**Comment by elingg** [comment]
This is a configuration value. Please set this up in your mesos-site.xml configuration before compiling, https://github.com/mesosphere/hdfs/blob/master/conf/mesos-site.xml#L83.

**Comment by F21** [comment]
I do have `mesos.native.library` pointing to the right place: `/opt/test/mesos/lib/libmesos.so`, but the problem is that it's not reading the value I have assigned to `LD_LIBRARY_PATH` and is having trouble loading shared libraries like `libsasl2.so`.

**Comment by elingg** [comment]
Please set mesos-site.xml prior to compiling it so it is propagated to the executors. hdfs-site.xml is propagated to executors if you configure this at runtime, but not mesos-site.xml as described in the readme. We do plan on implementing this for meso-site.xml along with other configuration improvements as part of our roadmap.

**Comment by F21** [comment]
Adding the following entry to `mesos-site.xml` and recompiling fixed it for me:

```xml
<property>
    <name>mesos.hdfs.ld-library-path</name>
    <value>/opt/test/mesos/lib</value>
  </property>
```
