### ISSUE TITLE
Config file needs to work for all settings / Readme Description

### ISSUE THREAD

**Issue by elingg** [mesosphere/hdfs#26]
Currently, the hdfs-site.xml config file allows us to set all hdfs related configurations and some other framework configurations. We need to make sure we can configure all config settings used by the framework and include documentation for this.

**Comment by adam-mesos** [comment]
Is this supposed to include the fact that non-default mesos-site.xml settings don't seem to take effect? Or is that a new/different issue?

**Comment by elingg** [comment]
Yes, we need to make sure that updating mesos-site.xml and hdfs-site.xml overrides all default settings. We also need to make sure rational defaults values are in place for mesos-site.xml and hdfs-site.xml.
