### ISSUE TITLE
Error: JAVA_HOME is not set and could not be found.

### ISSUE THREAD

**Issue by arindamchoudhury** [mesosphere/hdfs#261]
How can I set the JAVA_HOME?

I am getting this error:
I0617 15:15:41.516604 39797 fetcher.cpp:379] Fetching URI 'hdfs://hdfs/hadoop-2.7.2.tar.gz'
I0617 15:15:41.516626 39797 fetcher.cpp:250] Fetching directly into the sandbox directory
I0617 15:15:41.516644 39797 fetcher.cpp:187] Fetching URI 'hdfs://hdfs/hadoop-2.7.2.tar.gz'
E0617 15:15:41.540443 39797 shell.hpp:93] Command 'hadoop version 2>&1' failed; this is the output:
Error: JAVA_HOME is not set and could not be found.
Failed to fetch 'hdfs://hdfs/hadoop-2.7.2.tar.gz': Failed to create HDFS client: Failed to execute 'hadoop version 2>&1'; the command was either not found or exited with a non-zero exit status: 1

**Comment by muemich** [comment]
Hi, how did you solve this issue? I run into the same, but JAVA_HOME is set

**Comment by arindamchoudhury** [comment]
I set it in the etc/hadoop/hadoop-env.sh

**Comment by nitinmax10** [comment]
I set all the things but still I am getting the following error:

/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: syntax error near unexpected token `('
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: `﻿# Licensed to the Apache Software Foundation (ASF) under one'
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: syntax error near unexpected token `('
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: `﻿# Licensed to the Apache Software Foundation (ASF) under one'
starting resourcemanager, logging to /home/nitin/Software/hadoop-2.7.3/logs/yarn-nitin-resourcemanager-Clavax-PC-48.out
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: syntax error near unexpected token `('
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: `﻿# Licensed to the Apache Software Foundation (ASF) under one'
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: syntax error near unexpected token `('
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: `﻿# Licensed to the Apache Software Foundation (ASF) under one'
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: syntax error near unexpected token `('
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: `﻿# Licensed to the Apache Software Foundation (ASF) under one'
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: syntax error near unexpected token `('
/home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: `﻿# Licensed to the Apache Software Foundation (ASF) under one'
localhost: /home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: syntax error near unexpected token `('
localhost: /home/nitin/Software/hadoop-2.7.3/etc/hadoop/hadoop-env.sh: line 1: `﻿# Licensed to the Apache Software Foundation (ASF) under one'
localhost: Error: JAVA_HOME is not set and could not be found.


And I have checked the (hadoop-env.sh)file 100 times. How to resolve it.
