### ISSUE TITLE
mesosphere/hdfs:Could not find or load main class org.apache.mesos.hdfs.scheduler.Main

### ISSUE THREAD

**Issue by BhavnaChoubey** [mesosphere/hdfs#264]
I tried the same steps mentioned in URL https://github.com/mesosphere/hdfs but on running ./bin/hdfs-mesos got error as :
Error: Could not find or load main class org.apache.mesos.hdfs.scheduler.Main
Any idea about the same ?

**Comment by BhavnaChoubey** [comment]
Issue has been resolved by following the steps :

wget https://github.com/mesosphere/hdfs/archive/0.1.6.tar.gz
tar -xvf 0.1.6.tar.gz
cd hdfs-0.1.6 
./bin/build-hdfs
cd build/hdfs-mesos-0.1.6
./bin/hdfs-mesos

Also had changed JAVA_HOME to jdk

**Comment by rspan68** [comment]
I downloaded the 0.1.6.tar.gz archive but when sudo ./bin/build-hdfs i am receiving the following error, does anybody know how to overcome it?

FAILURE: Build failed with an exception.

* What went wrong:
Could not create service of type TaskArtifactStateCacheAccess using TaskExecutionServices.createCacheAccess().
> Failed to create parent directory '/opt/mesos-hdfs-build/hdfs/hdfs-0.1.6/.gradle' when creating directory '/opt/mesos-hdfs-build/hdfs/hdfs-0.1.6/.gradle/2.8/taskArtifacts'
