### ISSUE TITLE
Could not find or load main class org.apache.mesos.hdfs.scheduler.Main

### ISSUE THREAD

**Issue by jomach** [mesosphere/hdfs#266]
Hi Guys, I´m trying out this hdfs on mesos but I´m getting this error:

root@bumby-chair:~/hdfs/build/hdfs-mesos-0.1.5# ./bin/hdfs-mesos
Error: Could not find or load main class org.apache.mesos.hdfs.scheduler.Main

what I don´t unterstand is do I need to install hdfs before and then start it we this hdfs-mesos ? I espect that this repo do all this stuff...

thx

**Comment by jomach** [comment]
So I get the error out. the scheduler libs were not compiled if you use the nocompile parameter.

**Comment by triclambert** [comment]
Glad you figured it out.  Sorry we missed this.

**Comment by jomach** [comment]
I will make a pr for the Script that Compiles all the stuf .
