### ISSUE TITLE
Restore Data and HDFS Nodes upon Relaunch of Framework

### ISSUE THREAD

**Issue by elingg** [mesosphere/hdfs#32]
If the framework is killed and relaunched, the HDFS Nodes should be restored with data intact if possible. For example, the same host and data files should be used for a Name Node that was previously running.

**Comment by adam-mesos** [comment]
@elingg Can this be closed after the latest round of failure-handling changes and testing? I.e. #31

**Comment by elingg** [comment]
Indeed!
