### ISSUE TITLE
Scheduler HA

### ISSUE THREAD

**Issue by elingg** [mesosphere/hdfs#33]
If the scheduler dies and a new scheduler is started after the failure timeout has elapsed, the new scheduler needs to be able to register successfully with a unique framework id. Reregistration (with the same framework id) is done if the failover timeout has not elapsed, and registration is done (with a new framework id) if the failover timeout has elapsed.

**Comment by elingg** [comment]
Set failover timeout to infinity.

**Comment by adam-mesos** [comment]
Resolved by #72
