### ISSUE TITLE
Run with Mesos DNS

### ISSUE THREAD

**Issue by elingg** [mesosphere/hdfs#48]
-Framework name needs to be configurable
-Tasks need meaningful names, i.e. add code to call the name nodes primary and secondary to distinguish them

**Comment by nicgrayson** [comment]
The namenodes can switch between active and standby though. Naming them nn1 and nn2 like the config would make sense imo.

**Comment by elingg** [comment]
Good point. Primary and Secondary is different than Active and Standby, but it might confuse people. Perhaps nn1 and nn2 would be a good option.

**Comment by elingg** [comment]
Another thought on this. We may not need to distinguish between the NN's and testing with Mesos DNS might be enough to close this issue. Since we will not know which one is active and standby, distinguishing the task names may or may not be necessary. Mesos DNS would enable us to find both Name Nodes and then we can call getServiceState to see which one is active. Let me know what everyone thinks!

**Comment by adam-mesos** [comment]
After today's discussion, we may want separate nn1 and nn2 dns entries, which would then be the "hostnames" used in the actual nn1/nn2 config parameters.

**Comment by abhay-agarwal** [comment]
Closing this issue due to 0.1.0
