### ISSUE TITLE
Rewrite Framework in Scala

### ISSUE THREAD

**Issue by nicgrayson** [mesosphere/hdfs#50]
There is a lot that needs to be refactored in this project. I think moving to scala would ease this pain drastically.

**Comment by elingg** [comment]
HDFS is written in Java. At this time, we don't want to add a Scala dependency for customer and partners who are interested in this framework. We also want have different languages for different Mesos frameworks so Java is important. There are Mesos bindings in Scala, Java, Golang, Python, and Haskell currently. Of course frameworks can also be written in C++.

**Comment by nicgrayson** [comment]
Fair enough.
