### ISSUE TITLE
Executor namenode is attempting to pull AWS tgz file

### ISSUE THREAD

**Issue by jtfogarty** [mesosphere/hdfs#62]
During startup of the namenode I get the below error in stderr;
Since I'm behind a corporate firewall, this is blocked.  What is the work around?

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0211 17:36:28.146543  8001 fetcher.cpp:76] Fetching URI 'https://s3-us-west-1.amazonaws.com/mesosphere-executors-public/hdfs-mesos-0.0.2.tgz'
I0211 17:36:28.146812  8001 fetcher.cpp:126] Downloading 'https://s3-us-west-1.amazonaws.com/mesosphere-executors-public/hdfs-mesos-0.0.2.tgz' to '/tmp/mesos/slaves/20150206-050517-734012572-5050-25424-S0/frameworks/20150209-143206-734012572-5050-5083-0001/executors/executor.namenode.NameNodeExecutor.1423697788085/runs/f1fbac22-2f2c-46cf-9a0e-cb676b4dcd48/hdfs-mesos-0.0.2.tgz'
E0211 17:38:35.575791  8001 fetcher.cpp:129] Error downloading resource: Couldn't connect to server
Failed to fetch: https://s3-us-west-1.amazonaws.com/mesosphere-executors-public/hdfs-mesos-0.0.2.tgz

**Comment by elingg** [comment]
Hello @jtfogarty, This PR will resolve this issue, https://github.com/mesosphere/hdfs/pull/44. I or one of my team members will be finishing this soon. 

As a workaround, you can simply change getExecUri() in ConfServer. This parameter can also be changed in mesos-site.xml.
