### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by elingg** [mesosphere/hdfs#7]
Handle authentication in HDFS/ mesos.

**Comment by T0aD** [comment]
I can relate to that, apparently the hdfs-mesos framework is unable to authenticate to the mesos-masters, I failed to find any hint in the code, documentation or configuration.

**Comment by elingg** [comment]
@gabrielhartmann is currently investigating framework authentication so this feature is in progress

**Comment by gabrielhartmann** [comment]
@T0aD: See PR #175.  The config (principal and secret) must be set appropriately on the HDFS scheduler side.  The mesos master must also be setup with the same credentials for authentication.  See [the documentation regarding --credentials](http://mesos.apache.org/documentation/latest/configuration/).

**Comment by T0aD** [comment]
Hi, I was actually patching hdfs-mesos and I managed to make it register to
the Mesos cluster, I will check that out as soon as I'm at the office, it's
midnight here already ;)


On Wed, Aug 19, 2015 at 11:22 PM, Gabriel Hartmann <notifications@github.com

**Comment by elingg** [comment]
I got your other note that it worked for you @T0aD! Will close out this issue as we will be merging the PR soon.

**Comment by T0aD** [comment]
Yes indeed, I was able to build the tarball and have hdfs register to mesos, great job !
