### ISSUE TITLE
Don't wait forever for dead nodes to recover

### ISSUE THREAD

**Issue by adam-mesos** [mesosphere/hdfs#80]
After a brief timeout (~1-2 minutes), it should be assumed that a deadJournalNode/etc. is not coming back and that another one should be started elsewhere. Otherwise, a machine failure will cause the framework to hang.

**Comment by elingg** [comment]
@adam-mesos, can we close this with the latest PR since we are no longer hanging forever and have a timeout? Perhaps you can open a new PR related to removing the timeout entirely for datanodes.

**Comment by adam-mesos** [comment]
Resolved by https://github.com/mesosphere/hdfs/pull/94
